name: Create Windows VM
on:
  workflow_dispatch:
    inputs:
      vm_name:
        description: 'Name of the VM to create'
        required: true
        default: 'my-windows-vm'

env:
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
permissions:
  id-token: write
  contents: read
jobs:
  create-vm:
    runs-on: ubuntu-latest
    environment: dev


    steps:
      - name: Checkout repository
        uses: actions/checkout@v2


      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # - name: Azure login
        # uses: azure/login@v2
        # with:
          # creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
      - name: Initialize Terraform
        run: terraform init

      - name: terraform plan
        run: terraform plan -var "vm_name=${{ github.event.inputs.vm_name }}"
      - name: Apply Terraform
        run: terraform apply -var "vm_name=${{ github.event.inputs.vm_name }}" -auto-approve